/**
 * Fleet Coordinator Agent — ROUTINE Tier
 *
 * Tracks vehicle maintenance, monitors fleet status, alerts before due dates.
 * Generic fleet management — vehicle list and technician contacts come from company config.
 *
 * Reports to: CEO Agent
 * Skills: fleet-coordinator
 * Model: claude-haiku-4-5 (ROUTINE tier — structured, repeatable work)
 *
 * Scheduled: Daily 6AM fleet status check
 */
import { BaseAgent } from './base-agent.js';
import type { AgentConfig, Issue } from './types.js';
import type { ModelTier } from '../models/router.js';

export class FleetCoordinatorAgent extends BaseAgent {
  readonly role = 'fleet_coordinator';
  readonly roleLabel = 'Fleet Coordinator';
  readonly modelTier: ModelTier = 'ROUTINE';

  readonly roleMission = `You are the Fleet Coordinator. Your mission is to:
1. Monitor the status of ALL company vehicles from the fleet roster (loaded from company config)
2. Track maintenance schedules and alert 7 DAYS before any maintenance is due
3. Run a daily fleet status check every morning to ensure all vehicles are operational
4. Flag any vehicle with known issues (loaded from company config notes) when it's assigned
5. Coordinate with the designated maintenance technician (from company config) for repairs
6. Keep maintenance records updated in the fleet management system

Fleet data comes from company configuration — vehicle roster, maintenance schedules,
technician contacts, and any vehicle-specific notes are all injected at runtime.

Your daily check should:
- Verify each vehicle's operational status
- Check maintenance due dates against today's date
- Flag any vehicles overdue for maintenance
- Report fleet readiness percentage`;

  readonly successMetrics = `- Maintenance alerts: every due date flagged 7+ days in advance
- Fleet readiness: daily status report generated by 6:30 AM
- Zero surprise breakdowns: proactive maintenance tracking
- Record accuracy: all maintenance events logged in the system
- Issue escalation: mechanical problems flagged to human within 1 hour`;

  protected override buildMessages(
    config: AgentConfig,
    issue: Issue
  ): Array<{ role: 'user' | 'assistant'; content: string }> {
    const baseMessages = super.buildMessages(config, issue);

    const fleetContext = `

## Fleet Coordinator Skills
- Get fleet status: { "skill": "fleet-coordinator", "method": "getFleetStatus", "params": {} }
- Check vehicle availability: { "skill": "fleet-coordinator", "method": "checkAvailability", "params": { "vehicle_id": "...", "date": "YYYY-MM-DD" } }
- Log maintenance event: { "skill": "fleet-coordinator", "method": "logMaintenance", "params": { "vehicle_id": "...", "type": "...", "notes": "..." } }
- Get maintenance schedule: { "skill": "fleet-coordinator", "method": "getMaintenanceSchedule", "params": { "vehicle_id": "..." } }

CRITICAL RULES:
- Vehicle roster and notes come from company config — NEVER hardcode vehicle IDs
- Check company config for any vehicle-specific flags or warnings
- Maintenance technician contact is in company config — reference it, don't hardcode
- Alert threshold is 7 days before due — configurable per company`;

    baseMessages[0] = {
      role: 'user',
      content: baseMessages[0].content + fleetContext,
    };

    return baseMessages;
  }

  protected override getTemperature(): number {
    return 0.2; // Precise — maintenance tracking needs accuracy
  }
}
